In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
theta=np.linspace(0.01,1,10)
alpha=np.array([0,0.05,0.1,0.2])

Pcr = lambda theta, alpha: np.sin(theta)/(np.tan(theta)+alpha)

Resultados=Pcr(theta,alpha[0])
print(Resultados)


[0.99995    0.99280864 0.9736664  0.94275467 0.9004471  0.84725511
 0.78382167 0.71091354 0.62941203 0.54030231]


In [12]:
Resultados=np.zeros([len(alpha),len(theta)])
print(Resultados)

for i, coeficiente in enumerate(alpha):
    Resultados[i,:]=Pcr(theta,alpha[i])
    
print(Resultados)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.99995    0.99280864 0.9736664  0.94275467 0.9004471  0.84725511
  0.78382167 0.71091354 0.62941203 0.54030231]
 [0.16666296 0.70179782 0.80233274 0.82600107 0.81598612 0.78467621
  0.73729048 0.67671072 0.60491365 0.52349567]
 [0.0909073  0.54271723 0.68227458 0.73497903 0.74601107 0.73070574
  0.69597431 0.6456479  0.58225091 0.50770307]
 [0.04761818 0.37342459 0.52512037 0.6022483  0.63679424 0.64234415
  0.62583358 0.59135808 0.5416646  0.47881375]]
